---
- name: Ensure MariaDB is running
  systemd:
    name: mariadb
    state: started

- name: Add Galera SST user
  mysql_user:
    login_user: root
    name: "{{ galera_sst_user }}"
    host: "%"
    password: "{{ galera_sst_pass }}"
    priv: "*.*:ALTER ROUTINE, ALTER, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE USER, CREATE VIEW, CREATE, DELETE, EVENT, EXECUTE, INDEX, INSERT, LOCK TABLES, PROCESS, REFERENCES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SELECT, SHOW DATABASES, SHOW VIEW, TRIGGER, UPDATE"
